name: Ping Google

on:
  push:
    branches:
      - main

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Ping Google
      run: ping -c 4 google.com
