name: Call API

on:
  workflow_dispatch:
    inputs:
      message:
        required: true

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "2022-12-11T01:42:20"
      - name: Call API
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        run: |
          echo "Calling API..."
          curl -X GET 

