name: Call API

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        run: |
          echo "Calling API..."
          curl -X GET $API_ENDPOINT
