name: Call API

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Set up timestamp
        id: timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Call API
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        run: |
          echo "Calling API..."
          curl -X GET $API_ENDPOINT
